# NumPy 常用方法示例 (每个示例独立单元格)

In [1]:
import numpy as np
import math

In [2]:
# 1. np.array
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [3]:
# 2. np.arange
arr = np.arange(1, 10, 2)
print(arr)

[1 3 5 7 9]


In [4]:
# 3. np.linspace
arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [5]:
# 4. np.logspace
arr = np.logspace(0, 2, 5)
print(arr)

[  1.           3.16227766  10.          31.6227766  100.        ]


In [6]:
# 5. np.zeros
arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# 6. np.ones
arr = np.ones((2, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# 7. np.full
arr = np.full((2, 2), 99)
print(arr)

[[99 99]
 [99 99]]


In [9]:
# 8. np.empty
arr = np.empty((2, 2))
print(arr)  # 内容不确定

[[0.25 0.5 ]
 [0.75 1.  ]]


In [10]:
# 9. np.eye
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# 10. np.identity
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# 11. np.fromfunction
def func(i, j):
    return i + j
arr = np.fromfunction(func, (3, 3), dtype=int)
print(arr)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [13]:
# 12. np.fromiter
iterable = range(5)
arr = np.fromiter(iterable, dtype=float)
print(arr)

[0. 1. 2. 3. 4.]


In [14]:
# 13. np.fromstring
s = '1 2 3 4'
arr = np.fromstring(s, dtype=int, sep=' ')
print(arr)

[1 2 3 4]


In [15]:
# 14. np.copy
original = np.array([1, 2, 3])
arr_copy = np.copy(original)
arr_copy[0] = 99
print(original, arr_copy)

[1 2 3] [99  2  3]


In [16]:
# 15. np.asarray
x = [1, 2, 3]
arr = np.asarray(x)
print(arr)

[1 2 3]


In [17]:
# 16. np.asanyarray
x = np.matrix([[1,2],[3,4]])
arr = np.asanyarray(x)
print(type(arr))

<class 'numpy.matrix'>


In [18]:
# 17. np.asfarray
arr = np.asarray([1, 2, 3], dtype=np.float32)
print(arr.dtype)

float32


In [19]:
# 18. np.ascontiguousarray
arr = np.ascontiguousarray([[1, 2, 3], [4, 5, 6]])
print(arr.flags['C_CONTIGUOUS'])

True


In [20]:
# 19. np.asfortranarray
arr = np.asfortranarray([[1, 2], [3, 4]])
print(arr.flags['F_CONTIGUOUS'])

True


In [21]:
# 20. np.atleast_1d
arr = np.atleast_1d(5)
print(arr, arr.shape)

[5] (1,)


In [22]:
# 21. np.atleast_2d
arr = np.atleast_2d([1, 2, 3])
print(arr, arr.shape)

[[1 2 3]] (1, 3)


In [23]:
# 22. np.atleast_3d
arr = np.atleast_3d([1, 2, 3])
print(arr.shape)

(1, 3, 1)


In [24]:
# 23. arr.shape
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d.shape)

(2, 3)


In [25]:
# 24. arr.ndim
print(arr_2d.ndim)

2


In [26]:
# 25. arr.size
print(arr_2d.size)

6


In [27]:
# 26. arr.dtype
print(arr_2d.dtype)

int64


In [28]:
# 27. arr.itemsize
print(arr_2d.itemsize)

8


In [29]:
# 28. arr.nbytes
print(arr_2d.nbytes)

48


In [30]:
# 29. arr.T
print(arr_2d.T)

[[1 4]
 [2 5]
 [3 6]]


In [31]:
# 30. arr.flat
print(list(arr_2d.flat))

[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6)]


In [32]:
# 31. arr.base
sub_arr = arr_2d[0, :]
print(sub_arr.base is arr_2d)

True


In [33]:
# 32. np.reshape
arr = np.arange(6)
arr_reshaped = arr.reshape((2, 3))
print(arr_reshaped)

[[0 1 2]
 [3 4 5]]


In [34]:
# 33. ravel
print(arr_reshaped.ravel())

[0 1 2 3 4 5]


In [35]:
# 34. flatten
print(arr_reshaped.flatten())

[0 1 2 3 4 5]


In [36]:
# 35. expand_dims
x = np.array([1, 2, 3])
y = np.expand_dims(x, axis=0)
print(y.shape)

(1, 3)


In [37]:
# 36. squeeze
x = np.array([[[1, 2, 3]]])
y = np.squeeze(x)
print(y.shape)

(3,)


In [38]:
# 37. swapaxes
arr_2d = np.array([[1,2,3],[4,5,6]])
swapped = np.swapaxes(arr_2d, 0, 1)
print(swapped)

[[1 4]
 [2 5]
 [3 6]]


In [39]:
# 38. moveaxis
arr_3d = np.ones((2, 3, 4))
moved = np.moveaxis(arr_3d, 0, -1)
print(moved.shape)

(3, 4, 2)


In [40]:
# 39. concatenate
a = np.array([1, 2])
b = np.array([3, 4])
c = np.concatenate((a, b))
print(c)

[1 2 3 4]


In [41]:
# 40. vstack
a = np.array([1,2])
b = np.array([3,4])
c = np.vstack((a,b))
print(c)

[[1 2]
 [3 4]]


In [42]:
# 41. hstack
a = np.array([[1],[2]])
b = np.array([[3],[4]])
c = np.hstack((a,b))
print(c)

[[1 3]
 [2 4]]


In [43]:
# 42. dstack
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.dstack((a, b))
print(c.shape)

(2, 2, 2)


In [44]:
# 43. stack
a = np.array([1, 2])
b = np.array([3, 4])
c = np.stack((a, b), axis=0)
print(c)

[[1 2]
 [3 4]]


In [45]:
# 44. split
arr = np.arange(9)
splitted = np.split(arr, 3)
print(splitted)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [46]:
# 45. array_split
arr = np.arange(10)
splitted = np.array_split(arr, 3)
print(splitted)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [47]:
# 46. hsplit
arr = np.arange(6).reshape(2,3)
splitted = np.hsplit(arr, 3)
print(splitted)

[array([[0],
       [3]]), array([[1],
       [4]]), array([[2],
       [5]])]


In [48]:
# 47. vsplit
arr = np.arange(6).reshape(2,3)
splitted = np.vsplit(arr, 2)
print(splitted)

[array([[0, 1, 2]]), array([[3, 4, 5]])]


In [49]:
# 48. dsplit
arr = np.arange(8).reshape(2,2,2)
splitted = np.dsplit(arr, 2)
print([s.shape for s in splitted])

[(2, 2, 1), (2, 2, 1)]


In [50]:
# 49. block
A = np.block([
    [np.ones((2,2)), np.zeros((2,2))],
    [np.full((2,2), 7), np.eye(2)]
])
print(A)

[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [7. 7. 1. 0.]
 [7. 7. 0. 1.]]


In [51]:
# 50. 基本切片
arr = np.array([0, 1, 2, 3, 4])
print(arr[1:4])

[1 2 3]


In [52]:
# 51. 多维切片
arr_2d = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(arr_2d[:2, 1:])

[[1 2]
 [4 5]]


In [53]:
# 52. 布尔索引
arr = np.array([1, 2, 3, 4, 5])
bool_idx = arr > 2
print(arr[bool_idx])

[3 4 5]


In [54]:
# 53. 花式索引
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]
print(arr[idx])

[10 30 50]


In [55]:
# 54. np.where
arr = np.array([10, 20, 30, 40])
result = np.where(arr > 25)
print(result)

(array([2, 3]),)


In [56]:
# 55. np.argwhere
arr = np.array([[1, 2], [3, 4]])
print(np.argwhere(arr > 2))

[[1 0]
 [1 1]]


In [57]:
# 56. np.nonzero
arr = np.array([0, 1, 0, 2, 3])
print(np.nonzero(arr))

(array([1, 3, 4]),)


In [58]:
# 57. np.take
arr = np.array([10, 20, 30, 40])
print(np.take(arr, [1,3]))

[20 40]


In [59]:
# 58. np.put
arr = np.array([10, 20, 30, 40])
np.put(arr, [0, 2], [99, 88])
print(arr)

[99 20 88 40]


In [60]:
# 59. np.choose
x = np.array([0, 1, 0])
choice_arrays = [np.array([10,20,30]), np.array([40,50,60])]
result = np.choose(x, choice_arrays)
print(result)

[10 50 30]


In [61]:
# 60. np.unique
arr = np.array([1, 2, 2, 3, 3, 3])
print(np.unique(arr))

[1 2 3]


In [62]:
# 61. np.in1d
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 4])
print(np.in1d(arr1, arr2))

[False  True False]


C:\Users\minqliu\AppData\Local\Temp\ipykernel_23488\2127864927.py:4: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d(arr1, arr2))


In [63]:
# 62. np.intersect1d
print(np.intersect1d(arr1, arr2))

[2]


In [64]:
# 63. np.union1d
print(np.union1d(arr1, arr2))

[1 2 3 4]


In [65]:
# 64. np.setdiff1d
print(np.setdiff1d(arr1, arr2))

[1 3]


In [66]:
# 65. np.setxor1d
print(np.setxor1d(arr1, arr2))

[1 3 4]


In [67]:
# 66. np.sort
arr = np.array([3, 1, 2])
print(np.sort(arr))

[1 2 3]


In [68]:
# 67. arr.sort (就地)
arr.sort()
print(arr)

[1 2 3]


In [69]:
# 68. np.argsort
arr = np.array([3, 1, 2])
print(np.argsort(arr))

[1 2 0]


In [70]:
# 69. np.lexsort
names = np.array(['Bob','Alice','Bob','Charlie'])
grades = np.array([70,90,70,80])
idx = np.lexsort((grades, names))
print(idx)

[1 0 2 3]


In [71]:
# 70. np.searchsorted
arr = np.array([1,2,3,4,5])
idx = np.searchsorted(arr, 3)
print(idx)

2


In [72]:
# 71. np.partition
arr = np.array([7,2,3,1,5])
parted = np.partition(arr, 2)
print(parted)

[1 2 3 5 7]


In [73]:
# 72. np.argpartition
arr = np.array([7,2,3,1,5])
print(np.argpartition(arr, 2))

[3 1 2 4 0]


In [74]:
# 73. np.max / np.min
arr = np.array([1, 2, 3, 4])
print(np.max(arr), np.min(arr))

4 1


In [75]:
# 74. np.argmax / np.argmin
print(np.argmax(arr), np.argmin(arr))

3 0


In [76]:
# 75. np.ptp
arr2 = np.array([1,3,7,2])
print(np.ptp(arr2))

6


In [77]:
# 76. np.mean
arr = np.array([1,2,3,4])
print(np.mean(arr))

2.5


In [78]:
# 77. np.median
print(np.median(arr))

2.5


In [79]:
# 78. np.average
print(np.average(arr, weights=[1,2,3,4]))

3.0


In [80]:
# 79. np.std
print(np.std(arr))

1.118033988749895


In [81]:
# 80. np.var
print(np.var(arr))

1.25


In [82]:
# 81. np.sum
print(np.sum(arr))

10


In [83]:
# 82. np.prod
print(np.prod(arr))

24


In [84]:
# 83. np.cumsum
print(np.cumsum(arr))

[ 1  3  6 10]


In [85]:
# 84. np.cumprod
print(np.cumprod(arr))

[ 1  2  6 24]


In [86]:
# 85. np.percentile
arr = np.array([1,2,3,4,5])
print(np.percentile(arr, 50))

3.0


In [87]:
# 86. np.quantile
print(np.quantile(arr, 0.25))

2.0


In [88]:
# 87. np.clip
arr = np.array([1,2,3,4])
print(np.clip(arr, 2, 3))

[2 2 3 3]


In [89]:
# 88. np.round / np.around
x = np.array([1.234, 2.345, 3.456])
print(np.round(x,1))

[1.2 2.3 3.5]


In [90]:
# 89. np.floor
print(np.floor(x))

[1. 2. 3.]


In [91]:
# 90. np.ceil
print(np.ceil(x))

[2. 3. 4.]


In [92]:
# 91. np.trunc
print(np.trunc(x))

[1. 2. 3.]


In [93]:
# 92. np.rint
x = np.array([1.5, 2.5, 3.1])
print(np.rint(x))

[2. 2. 3.]


In [94]:
# 93. np.fix
x = np.array([2.1, 2.9, -3.2])
print(np.fix(x))

[ 2.  2. -3.]


In [95]:
# 94. np.isfinite / isinf / isnan
arr = np.array([1, np.inf, np.nan])
print(np.isfinite(arr), np.isinf(arr), np.isnan(arr))

[ True False False] [False  True False] [False False  True]


In [96]:
# 95. np.isclose
a=0.3
b=0.1+0.2
print(np.isclose(a,b))

True


In [97]:
# 96. np.allclose
arr1 = np.array([1.0,2.0,3.0])
arr2 = np.array([1.0000001,2.0000001,3.0])
print(np.allclose(arr1, arr2))

True


In [98]:
# 97. np.array_equal
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
print(np.array_equal(arr1, arr2))

True


In [99]:
# 98. np.array_equiv
arr1 = np.array([1,1,1])
arr2 = np.array([[1,1,1],[1,1,1]])
print(np.array_equiv(arr1, arr2))

True


In [100]:
# 99. np.count_nonzero
arr = np.array([0,1,2,0,3])
print(np.count_nonzero(arr))

3


In [101]:
# 100. np.nan_to_num
arr = np.array([1, np.nan, np.inf])
print(np.nan_to_num(arr))

[1.00000000e+000 0.00000000e+000 1.79769313e+308]


In [102]:
# 101. np.logical_and / np.logical_or
a = np.array([True, False, True])
b = np.array([False, False, True])
print(np.logical_and(a,b), np.logical_or(a,b))

[False False  True] [ True False  True]


In [103]:
# 102. np.greater, np.equal
x = np.array([1,2,3])
y = np.array([2,2,2])
print(np.greater(x,y), np.equal(x,y))

[False False  True] [False  True False]


In [104]:
# 103. np.all
arr = np.array([True, True, False])
print(np.all(arr))

False


In [105]:
# 104. np.any
print(np.any(arr))

True


In [106]:
# 105. np.add / subtract / multiply
x = np.array([1,2,3])
y = np.array([4,5,6])
print(np.add(x,y), np.subtract(x,y), np.multiply(x,y))

[5 7 9] [-3 -3 -3] [ 4 10 18]


In [107]:
# 106. np.divide / floor_divide
print(np.divide(x,y), np.floor_divide(x,y))

[0.25 0.4  0.5 ] [0 0 0]


In [108]:
# 107. np.power
print(np.power(x,2))

[1 4 9]


In [109]:
# 108. np.mod
print(np.mod(y,x))

[0 1 0]


In [110]:
# 109. np.exp / np.exp2
arr = np.array([1,2,3])
print(np.exp(arr), np.exp2(arr))

[ 2.71828183  7.3890561  20.08553692] [2. 4. 8.]


In [111]:
# 110. np.log / np.log2 / np.log10
arr = np.array([1, math.e, math.e**2])
print(np.log(arr), np.log2(arr), np.log10(arr))

[0. 1. 2.] [0.         1.44269504 2.88539008] [0.         0.43429448 0.86858896]


In [112]:
# 111. np.log1p / np.expm1
arr = np.array([0,0.01,0.1])
print(np.log1p(arr), np.expm1(arr))

[0.         0.00995033 0.09531018] [0.         0.01005017 0.10517092]


In [113]:
# 112. np.abs
arr = np.array([-1,-2,3])
print(np.abs(arr))

[1 2 3]


In [114]:
# 113. np.negative / np.positive
arr = np.array([1, -2, 3])
print(np.negative(arr), np.positive(arr))

[-1  2 -3] [ 1 -2  3]


In [115]:
# 114. np.sign
arr = np.array([-5,0,5])
print(np.sign(arr))

[-1  0  1]


In [116]:
# 115. np.sin / np.cos / np.tan
x = np.array([0, np.pi/2, np.pi])
print(np.sin(x), np.cos(x), np.tan(x))

[0.0000000e+00 1.0000000e+00 1.2246468e-16] [ 1.000000e+00  6.123234e-17 -1.000000e+00] [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [117]:
# 116. np.arcsin / arccos / arctan
y = np.array([0,1,-1])
print(np.arcsin(y))

[ 0.          1.57079633 -1.57079633]


In [118]:
# 117. np.sinh / cosh / tanh
x = np.array([0,1,-1])
print(np.sinh(x), np.cosh(x), np.tanh(x))

[ 0.          1.17520119 -1.17520119] [1.         1.54308063 1.54308063] [ 0.          0.76159416 -0.76159416]


In [119]:
# 118. np.arcsinh / arctanh
x = np.array([0,1,2])
print(np.arcsinh(x), np.arctanh(x/3))

[0.         0.88137359 1.44363548] [0.         0.34657359 0.80471896]


In [120]:
# 119. np.deg2rad / rad2deg
deg = np.array([0,180,360])
print(np.deg2rad(deg))
rad = np.array([0, np.pi, 2*np.pi])
print(np.rad2deg(rad))

[0.         3.14159265 6.28318531]
[  0. 180. 360.]


In [121]:
# 120. np.hypot
x = np.array([3,5])
y = np.array([4,12])
print(np.hypot(x,y))

[ 5. 13.]


In [122]:
# 121. np.meshgrid
x = np.array([1,2,3])
y = np.array([10,20])
X, Y = np.meshgrid(x, y)
print(X, Y)

[[1 2 3]
 [1 2 3]] [[10 10 10]
 [20 20 20]]


In [123]:
# 122. np.broadcast_to
a = np.array([1,2,3])
b = np.broadcast_to(a, (3,3))
print(b)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [124]:
# 123. np.broadcast_arrays
a = np.array([1,2,3])
b = np.array([[10],[20],[30]])
A, B = np.broadcast_arrays(a, b)
print(A, B)

[[1 2 3]
 [1 2 3]
 [1 2 3]] [[10 10 10]
 [20 20 20]
 [30 30 30]]


In [125]:
# 124. np.dot
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(np.dot(x,y))

[[19 22]
 [43 50]]


In [126]:
# 125. np.vdot
a = np.array([1+2j, 3+4j])
b = np.array([5+6j, 7+8j])
print(np.vdot(a,b))

(70-8j)


In [127]:
# 126. np.inner
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.inner(a,b))

32


In [128]:
# 127. np.outer
print(np.outer(a,b))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [129]:
# 128. np.matmul
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(np.matmul(x,y))

[[19 22]
 [43 50]]


In [130]:
# 129. np.tensordot
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.tensordot(a,b,axes=1))

[[19 22]
 [43 50]]


In [131]:
# 130. np.einsum
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.einsum('i,i->', a, b)
print(c)

32


In [132]:
# 131. np.linalg.inv
mat = np.array([[1,2],[3,4]])
inv_mat = np.linalg.inv(mat)
print(inv_mat)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [133]:
# 132. np.linalg.det
print(np.linalg.det(mat))

-2.0000000000000004


In [134]:
# 133. np.linalg.matrix_rank
print(np.linalg.matrix_rank(mat))

2


In [135]:
# 134. np.linalg.eig
vals, vecs = np.linalg.eig(mat)
print(vals, vecs)

[-0.37228132  5.37228132] [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [136]:
# 135. np.linalg.eigvals
print(np.linalg.eigvals(mat))

[-0.37228132  5.37228132]


In [137]:
# 136. np.linalg.solve
A = np.array([[3,1],[1,2]])
b = np.array([9,8])
x = np.linalg.solve(A,b)
print(x)

[2. 3.]


In [138]:
# 137. np.linalg.norm
v = np.array([3,4])
print(np.linalg.norm(v))

5.0


In [139]:
# 138. np.linalg.qr
mat = np.array([[1,2],[3,4],[5,6]])
Q,R = np.linalg.qr(mat)
print(Q, R)

[[-0.16903085  0.89708523]
 [-0.50709255  0.27602622]
 [-0.84515425 -0.34503278]] [[-5.91607978 -7.43735744]
 [ 0.          0.82807867]]


In [140]:
# 139. np.linalg.cholesky
A = np.array([[4,6],[6,13]])
L = np.linalg.cholesky(A)
print(L)

[[2. 0.]
 [3. 2.]]


In [141]:
# 140. np.linalg.svd
A = np.array([[1,2],[3,4],[5,6]])
U, s, Vt = np.linalg.svd(A, full_matrices=False)
print(U, s, Vt)

[[-0.2298477   0.88346102]
 [-0.52474482  0.24078249]
 [-0.81964194 -0.40189603]] [9.52551809 0.51430058] [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [142]:
# 141. np.linalg.lstsq
A = np.array([[1,1],[1,2],[1,3]])
b = np.array([2,2.5,3.5])
x, residuals, rank, s = np.linalg.lstsq(A,b, rcond=None)
print(x, residuals, rank, s)

[1.16666667 0.75      ] [0.04166667] 2 [4.07914333 0.60049122]


In [143]:
# 142. fft / ifft
from numpy.fft import fft, ifft, fftn, ifftn, rfft, irfft
arr = np.array([1,2,3,4])
freq = fft(arr)
time_ = ifft(freq)
print(freq, time_)

[10.+0.j -2.+2.j -2.+0.j -2.-2.j] [1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [144]:
# 143. fftn / ifftn
arr_2d = np.array([[1,2],[3,4]])
freq_2d = fftn(arr_2d)
time_2d = ifftn(freq_2d)
print(freq_2d, time_2d)

[[10.+0.j -2.+0.j]
 [-4.+0.j  0.+0.j]] [[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [145]:
# 144. rfft / irfft
arr = np.array([1,2,3,4])
freq_real = rfft(arr)
time_real = irfft(freq_real)
print(freq_real, time_real)

[10.+0.j -2.+2.j -2.+0.j] [1. 2. 3. 4.]


In [146]:
# 145. np.poly1d
p = np.poly1d([1,2,3])
print(p(5))

38


In [147]:
# 146. np.polyval
coeffs = [1,2,3]
print(np.polyval(coeffs,5))

38


In [148]:
# 147. np.polyfit
x = np.array([0,1,2,3])
y = np.array([1,3,7,13])
cf = np.polyfit(x,y, deg=2)
print(cf)

[1. 1. 1.]


In [149]:
# 148. np.roots
coeffs = [1,2,1]
print(np.roots(coeffs))

[-1. -1.]


In [150]:
# 149. np.gradient
arr = np.array([1,2,4,7,11])
print(np.gradient(arr))

[1.  1.5 2.5 3.5 4. ]


In [151]:
# 150. np.diff
print(np.diff(arr))

[1 2 3 4]


In [152]:
# 151. np.ediff1d
arr_2d = np.array([[1,2,3],[4,5,6]])
print(np.ediff1d(arr_2d))

[1 1 1 1 1]


In [153]:
# 152. np.unwrap
angles = np.array([0, np.pi/2, np.pi, -3*np.pi/4])
print(np.unwrap(angles))

[0.         1.57079633 3.14159265 3.92699082]


In [154]:
# 153. np.trapz
x = np.array([0,1,2])
y = np.array([0,1,4])
print(np.trapz(y,x))

3.0


C:\Users\minqliu\AppData\Local\Temp\ipykernel_23488\897648374.py:4: DeprecationWarning: `trapz` is deprecated. Use `trapezoid` instead, or one of the numerical integration functions in `scipy.integrate`.
  print(np.trapz(y,x))


In [155]:
# 154. np.kron
A = np.array([[1,2],[3,4]])
B = np.array([[0,5],[6,7]])
print(np.kron(A,B))

[[ 0  5  0 10]
 [ 6  7 12 14]
 [ 0 15  0 20]
 [18 21 24 28]]


In [156]:
# 155. np.histogram
data = np.array([1,2,2,3,4,4,4,5])
hist,bins = np.histogram(data,bins=4)
print(hist,bins)

[1 2 1 4] [1. 2. 3. 4. 5.]


In [157]:
# 156. np.digitize
bins = [0,2,4,6]
print(np.digitize(data, bins))

[1 2 2 2 3 3 3 3]


In [158]:
# 157. np.bincount
arr = np.array([0,1,1,2,2,2])
print(np.bincount(arr))

[1 2 3]


In [159]:
# 158. np.cov
x = np.array([0,1,2])
y = np.array([2,1,0])
print(np.cov(x,y))

[[ 1. -1.]
 [-1.  1.]]


In [160]:
# 159. np.corrcoef
print(np.corrcoef(x,y))

[[ 1. -1.]
 [-1.  1.]]


In [161]:
# 160. np.nanmax / nanmin
arr = np.array([1, np.nan, 3])
print(np.nanmax(arr), np.nanmin(arr))

3.0 1.0


In [162]:
# 161. np.nanargmax / nanargmin
print(np.nanargmax(arr), np.nanargmin(arr))

2 0


In [163]:
# 162. np.nansum
print(np.nansum(arr))

4.0


In [164]:
# 163. np.nanmean
print(np.nanmean(arr))

2.0


In [165]:
# 164. np.nanstd / np.nanvar
arr = np.array([1, np.nan, 5])
print(np.nanstd(arr), np.nanvar(arr))

2.0 4.0


In [166]:
# 165. np.nancumsum / np.nancumprod
arr = np.array([1, np.nan, 2, 3])
print(np.nancumsum(arr), np.nancumprod(arr))

[1. 1. 3. 6.] [1. 1. 2. 6.]


In [167]:
# 166. np.random.rand
r = np.random.rand(2,3)
print(r)

[[0.70107684 0.78421294 0.06800185]
 [0.07091766 0.68622638 0.1399112 ]]


In [168]:
# 167. np.random.randn
r = np.random.randn(2,3)
print(r)

[[-1.18248356 -0.67300596  0.67198531]
 [-0.23331329  0.647586   -0.15205689]]


In [169]:
# 168. np.random.randint
r = np.random.randint(0,10,size=(2,3))
print(r)

[[1 9 6]
 [1 0 4]]


In [170]:
# 169. np.random.uniform
r = np.random.uniform(1,5,size=5)
print(r)

[1.00900519 1.92355541 2.8180942  3.34792559 1.47782878]


In [171]:
# 170. np.random.normal
r = np.random.normal(loc=0, scale=1, size=5)
print(r)

[-0.39682416  0.51424917 -0.79080725 -0.20995163 -0.89902034]


In [172]:
# 171. np.random.binomial
r = np.random.binomial(n=10, p=0.5, size=5)
print(r)

[6 7 5 4 5]


In [173]:
# 172. np.random.poisson
r = np.random.poisson(lam=5,size=5)
print(r)

[4 5 6 5 7]


In [174]:
# 173. np.random.beta
r = np.random.beta(a=2,b=5,size=5)
print(r)

[0.46199268 0.43315992 0.07217999 0.18954255 0.18800894]


In [175]:
# 174. np.random.exponential
r = np.random.exponential(scale=2.0,size=5)
print(r)

[ 1.38044134  1.18018499  0.10989858  0.09555416 10.71363988]


In [176]:
# 175. np.random.gamma
r = np.random.gamma(shape=2.0, scale=2.0, size=5)
print(r)

[6.16123896 2.51579241 8.40003217 4.09873316 3.84610768]


In [177]:
# 176. np.random.chisquare
r = np.random.chisquare(df=2, size=5)
print(r)

[2.5347835  0.15533243 3.19808368 7.97160871 2.77479636]


In [178]:
# 177. np.random.gumbel
r = np.random.gumbel(loc=0, scale=1, size=5)
print(r)

[ 0.20091207  0.65903775 -0.13460124 -1.53489178  1.08496221]


In [179]:
# 178. np.random.logistic
r = np.random.logistic(loc=0, scale=1, size=5)
print(r)

[ 2.91100763 -0.2259794  -0.72644531 -5.56130482  0.90797293]


In [180]:
# 179. np.random.laplace
r = np.random.laplace(loc=0, scale=1, size=5)
print(r)

[-1.00633288 -1.09834408 -0.08392512 -1.81321727 -0.53064222]


In [181]:
# 180. np.random.lognormal
r = np.random.lognormal(mean=0, sigma=1, size=5)
print(r)

[0.35927846 0.8852013  0.82353884 0.51964622 0.19257968]


In [182]:
# 181. np.random.multivariate_normal
mean = [0,0]
cov = [[1,0.5],[0.5,1]]
r = np.random.multivariate_normal(mean,cov,size=5)
print(r)

[[ 0.49319277 -1.26932335]
 [ 0.12885436  0.21247467]
 [-0.22592843  0.40213569]
 [ 1.52618007  1.84322818]
 [-0.24961351  0.79172781]]


In [183]:
# 182. np.random.choice
arr = np.array([10,20,30,40])
print(np.random.choice(arr,size=3))

[40 10 40]


In [184]:
# 183. np.random.permutation
arr = np.arange(5)
print(np.random.permutation(arr), arr)

[1 4 2 0 3] [0 1 2 3 4]


In [185]:
# 184. np.random.shuffle
arr = np.arange(5)
np.random.shuffle(arr)
print(arr)

[0 3 2 1 4]


In [186]:
# 185. np.random.seed
np.random.seed(42)
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]


In [187]:
# 186. np.random.get_state / set_state
state = np.random.get_state()
temp = np.random.rand(3)
np.random.set_state(state)
print(np.random.rand(3))

[0.59865848 0.15601864 0.15599452]


In [188]:
# 187. np.loadtxt / 188. np.savetxt
print('需要实际文件操作,此处略')

需要实际文件操作,此处略


In [189]:
# 189. np.genfromtxt
print('需要实际文件操作,此处略')

需要实际文件操作,此处略


In [190]:
# 190. np.load / np.save / np.savez
print('需要实际文件操作,此处略')

需要实际文件操作,此处略


In [191]:
# 191. np.who
print('交互式环境有效,此处略')

交互式环境有效,此处略


In [192]:
# 192. np.fromfile / 193. np.tofile
print('需要二进制文件操作,此处略')

需要二进制文件操作,此处略


In [193]:
# 194. np.memmap
print('需要大文件映射,此处略')

需要大文件映射,此处略


In [194]:
# 195. np.real_if_close
arr = np.array([1+1e-14j, 2+3j])
print(np.real_if_close(arr, tol=1000))

[1.+1.e-14j 2.+3.e+00j]


In [195]:
# 196. np.sort_complex
c = np.array([1+2j,1+1j,2+1j])
print(np.sort_complex(c))

[1.+1.j 1.+2.j 2.+1.j]


In [196]:
# 197. np.place
arr = np.array([1,2,3,4,5])
np.place(arr, arr>2, [99])
print(arr)

[ 1  2 99 99 99]


In [197]:
# 198. np.select
arr = np.array([1,2,3,4,5])
cond_list = [arr<3, arr>4]
choice_list = [arr*10, arr*-1]
res = np.select(cond_list, choice_list, default=arr)
print(res)

[10 20  3  4 -5]


In [198]:
# 199. np.array_split (见45)
print('已在 #45 示例')

已在 #45 示例


In [199]:
# 200. np.unravel_index / np.ravel_multi_index
idx = np.unravel_index(5, (2,3))
print(idx)
lin = np.ravel_multi_index((1,2), (2,3))
print(lin)

(np.int64(1), np.int64(2))
5
